---
title: "Modeling Occupancy and Abundance"
output:
  html_document:
    fig_caption: true
    theme: "journal"
    toc: true
    toc_float:
      smooth_scroll: true
---
prepared by: *Michael T. Hallworth*    
*Smithsonian Conservation Biology Institute : Migratory Bird Center*

Introduction
-------------
Point count data are a cost effective way of surveying large areas to answer ecological questions. For example, point count data can answer the questions:     

*  How many species are present in a given area?    
*  How many individuals of each species are there?  
* How has the community changed over time?  
* Which habitats is X species associated with?  

These are just a few of the possible questions that can be answered using point count data. However, the question of interest determines how the data should be analyzed. If the question deals with *how many species are present here?* then using occupancy modeling would be a good fit. If the question is something like *How has the population size of Ovenbirds changed over time?*, then modeling abundance is more appropriate.

Regardless of the question - accounting for imperfect detection is important. Failing to account for imperfect detection biases estimates of either species richness or abundance low - unless all species and/or individuals are detected perfectly. This is unlikely given that the study organisms are animals and move, may have been siting on a nest during your visit, preening instead of singing, etc.  

The subsequent code illustrates how to use point count data to answer ecological questions while accounting for imperfect detection. In this tutorial we will use simulated data using 373 survey locations within Hubbard Brook Experimental Forest, NH that were visited three times during the 2015 breeding season. Three, 10 minute point count surveys were conducted along 15 transects spaced 500m apart. Each survey location was seperated by either 100m, or 200m. All species seen or heard within 50m and 100m of the point during the 10 min count were recorded.

**NOTE:** The code was written for analysis using BUGS language (JAGS, winBUGS, openBUGS, etc.)

Getting the data
-------------
```{r, warning=FALSE,error=FALSE,message=FALSE}
library(RCurl)

# Define the location of the data on GitHub
data_url <- "https://raw.githubusercontent.com/MTHallworth/OccAbun_Buler/master/data/OVEN.csv"

SiteCovs_url <- "https://raw.githubusercontent.com/MTHallworth/OccAbun_Buler/master/data/SiteCovariates.csv"
Date_url <- "https://raw.githubusercontent.com/MTHallworth/OccAbun_Buler/master/data/Date.csv"
Time_url <- "https://raw.githubusercontent.com/MTHallworth/OccAbun_Buler/master/data/Time.csv"
Observer_url <- "https://raw.githubusercontent.com/MTHallworth/OccAbun_Buler/master/data/Obs.csv"

# Get the data connection using RCurl 
data.url <- getURL(data_url)                
covs.url <- getURL(SiteCovs_url)
date.url <- getURL(Date_url)
time.url <- getURL(Time_url)
obs.url <- getURL(Observer_url)

# Read in the data 
OVEN <- read.csv(textConnection(data.url))
SiteCovs <- read.csv(textConnection(covs.url))
Date <- read.csv(textConnection(date.url))
Time <- read.csv(textConnection(time.url))
Obs <- read.csv(textConnection(obs.url))

Time[is.na(Time)]<-0
Date[is.na(Date)]<-0
Obs[is.na(Obs)]<-0

# Rename the first column in SiteCovs from X to Plot
names(SiteCovs)[1]<-"Plot"
names(Date) <- c("Rep.1","Rep.2","Rep.3","Rep.4")
names(Time) <- c("Rep.1","Rep.2","Rep.3","Rep.4")
names(Obs) <- c("Rep.1","Rep.2","Rep.3","Rep.4")

# Inspect first 5 rows
head(OVEN)
```
 
The number of individuals were counted within the 10min point count. Here we convert the number of individuals to presence / absence. 

```{r}
OVENocc<-OVEN
OVENocc[OVENocc>1]<-1

head(OVENocc)
```

Occupancy
----------
```{r}
###################################################################################
#
# Specify model in BUGS language
#
###################################################################################

cat("
model {
###################################################################################
#
#             Priors
#
################################################################################### 
# Hyperpriors
mu.lpsi ~ dnorm(0,0.01)
tau.lpsi <- pow(sd.lpsi, -2)
sd.lpsi ~ dunif(0,8)

mu.beta ~ dnorm(0,0.01)
tau.beta <- pow(sd.beta, -2)
sd.beta ~ dunif(0,5)

mu.lp ~ dnorm(0,0.01)
tau.lp <- pow(sd.lp, -2)
sd.lp ~ dunif(0,3)

mu.betaP ~ dnorm(0,0.01)
tau.betaP <- pow(sd.betaP, -2)
sd.betaP ~ dunif(0,3)

# priors 
   lpsi ~ dnorm(mu.lpsi, tau.lpsi)               # Hyperparams
   lp ~ dnorm(mu.lp, tau.lp)

for(c in 1:ncovs){                                  # Richness Covs
   beta[c] ~ dnorm(mu.beta, tau.beta)
 } #ncovs
 
for(d in 1:pcovs){                                  # Detection Covs
   betaP[d] ~ dnorm(mu.betaP, tau.betaP)
}  #pcovs


##################################################################################
#
# Likelihood
# Ecological model for true occurrence (process model)
#
##################################################################################

for (i in 1:plots) { 

      logit(psi[i])<-lpsi + beta[1]*Elev[i]+beta[2]*Elev2[i]+beta[3]*Slope[i] + beta[4]*Aspect[i]

      z[i] ~ dbern(psi[i])

} #nplots

##################################################################################
#
# Observation model for replicated detection/nondetection observations
#
##################################################################################

   for (i in 1:plots){
      for(j in 1:reps){

         logit(p[i,j]) <-lp+betaP[1]*time[i,j]+betaP[2]*date[i,j]+betaP[3]*obsvr[i,j] 

         y[i,j] ~ dbern(z[i] * p[i,j]) # True Occupancy state * detection 

      } #nreps
   }    #nschwarz
   
##################################################################################
#
# Derived quantities
#
##################################################################################


##################################################################################

} # End Model
",fill=TRUE,file = "Occupancy.txt")
```

```{r}
#
zint<-function(x){
  b<-apply(x,1,sum)
  b[b>1]<-1
  return(b)
}

set.seed(04823)
inits <- function() list(z = zint(OVENocc),
                         mu.lpsi=rnorm(1,0,0.1),
                         sd.lpsi=runif(1,0,8),
                         mu.beta=rnorm(1,0.1),
                         sd.beta=runif(1,0,5),
                         mu.lp=rnorm(1,0,0.1),
                         sd.lp=runif(1,0,3),
                         mu.betaP=rnorm(1,0,0.1),
                         sd.betaP=runif(1,0,3))
nchains<-3



win.data <- list(y = OVENocc,
                 ncovs = 4,
                 pcovs = 3, 
                 time = Time, 
                 date = Date,
                 obsvr = Obs,
                 plots = 373,
                 reps = 4,
                 Elev = SiteCovs$Elevation,
                 Elev2 = (SiteCovs$Elevation*SiteCovs$Elevation),
                 Slope = SiteCovs$Slope,
                 Aspect = SiteCovs$Aspect)
                 
parameters.to.save = c("psi","beta","p", "betaP")

library(jagsUI)
Sys.time()
a<-Sys.time()
z <- jags(model.file = "Occupancy.txt",
          data = win.data,
          inits = inits,
          parameters.to.save = parameters.to.save,
          n.iter = 100000,
          n.burnin = 50000, 
          n.thin = 20,
          n.chains = 3,
          n.adapt = 5000,
          parallel = TRUE)
Sys.time()-a
Sys.time()
```
